package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TestforblockeduserTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testforblockeduser() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(1050, 840));
        driver.findElement(By.id("user-name")).click();
        driver.findElement(By.id("user-name")).sendKeys("locked_out_user");
        driver.findElement(By.id("password")).click();
        driver.findElement(By.id("password")).sendKeys("secret_sauce");
        driver.findElement(By.id("login-button")).click();
        assertThat(driver.findElement(By.cssSelector("*[data-test=\"error\"]")).getText(), is("Epic sadface: Sorry, this user has been locked out."));
    }

    @Test
    public void Test_new() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(1050, 840));
        ClickElement("user-name");
        EnterDataInElement("user-name", "standard_user");
        ClickElement("password");
        EnterDataInElement("password", "secret_sauce");
        ClickElement("login-button");
        assertThat(driver.findElement(By.className("title")).getText(), is("PRODUCTS"));

    }

    @Test
    public void Test_description_of_item() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(1050, 840));
        ClickElement("user-name");
        EnterDataInElement("user-name", "standard_user");
        ClickElement("password");
        EnterDataInElement("password", "secret_sauce");
        ClickElement("login-button");
        ClickElement("item_2_title_link");
        assertThat(driver.findElement(By.cssSelector("*[class=\"inventory_details_desc large_size\"]")).getText(), is("Rib snap infant onesie for the junior automation engineer in development. Reinforced 3-snap bottom closure, two-needle hemmed sleeved and bottom won't unravel."));
    }

    //Additional methods
    void ClickElement (String idElement){
        driver.findElement(By.id(idElement)).click();
    }
    void EnterDataInElement (String idElement, String valueToType){
        driver.findElement(By.id(idElement)).sendKeys (valueToType);
    }
}




